name: eatonomy
description: Eatonomy
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.26+26

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:

#  device_preview: ^1.1.0

  #dependencies injection
  get_it: ^7.6.0


  #location
  location: ^5.0.3
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.0
  geolocator: ^10.0.0

  #for double tap error
  easy_debounce: ^2.0.3

  time_range: ^1.1.1

  #for rewsponsive
  flutter_screenutil: ^5.7.0

  #lotti file
  lottie: ^2.2.0
  #svg
  flutter_svg:

  #firebase
  #  cloud_firestore:
  #  firebase_core: 2.15.1
  #  firebase_messaging: 14.6.6
  flutter_local_notifications: ^15.1.0+1


  firebase_core: ^1.20.1
  #  firebase_analytics: ^9.1.0
  #  firebase_crashlytics: ^2.5.1
  firebase_messaging: ^12.0.2

  #  firebase_core: ^1.20.1
  #  firebase_crashlytics: ^2.5.1
  #  firebase_messaging: ^12.0.2




  #Device path get
  path_provider: ^2.0.13

  #print Log
  logger: ^2.0.1

  #bloc
  flutter_bloc: ^8.1.2
  hydrated_bloc: ^9.1.0

  #Getx
  get: ^4.6.5

  #hive db
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #locatligation
  easy_localization:

  #permision
  permission_handler: ^10.2.0



  #htp
  http: ^0.13.5
  dio: ^5.1.1

  #image
  image_picker: ^1.0.2
  camera: ^0.10.5+3
  cached_network_image: ^3.3.0


  #need dependency
  carousel_slider: ^4.2.1
  carousel_indicator: ^1.0.6
  flutter_animation_progress_bar: ^2.3.1
  pin_code_fields: ^8.0.1
  flutter_html: ^3.0.0-alpha.6

  #  ssl commerce
  flutter_sslcommerz: ^2.2.2-nullsafety.0
  fluttertoast: ^8.2.1

  #  youtube player
  youtube_player_flutter: ^8.1.2

  #  file picker
  file_picker: ^5.2.7

  #  rating bar
  flutter_rating_bar: ^4.0.1
  #  Screen sort
  screenshot: ^2.0.0
  image_gallery_saver: '^2.0.1'
  #timer
  quiver: ^3.2.1

  #Device info
  device_info_plus: ^9.0.2
  unique_identifier: ^0.3.0

  #cart icon count
  badges: ^3.1.1
  #timeline package:
  timeline_tile: ^2.0.0
  modal_bottom_sheet: ^3.0.0-pre
  dots_indicator: ^2.1.1
  weekday_selector: ^1.1.0

  grouped_list: ^5.1.2

  syncfusion_flutter_charts: ^23.2.6
  fl_chart: ^0.64.0


dependency_overrides:
  intl: ^0.19.0
  firebase_core_platform_interface: 4.5.1


  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

dev_dependencies:


  build_runner: ^2.4.6
  json_serializable:
  hive_generator: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1
flutter_icons:
  android: false
  ios: true
  image_path: "assets/images/logo.png"


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/images/
    - assets/lottie/
    - assets/icons/
    - assets/fonts/
    - shorebird.yaml

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:

    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-ExtraBold.ttf
        - asset: assets/fonts/Sora-Bold.ttf
        - asset: assets/fonts/Sora-ExtraLight.ttf
        - asset: assets/fonts/Sora-Light.ttf
        - asset: assets/fonts/Sora-Medium.ttf
        - asset: assets/fonts/Sora-Regular.ttf
        - asset: assets/fonts/Sora-SemiBold.ttf
        - asset: assets/fonts/Sora-Thin.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
